apiVersion: v1
kind: Service
metadata:
  name: conceptgraph-backend
  namespace: default
  labels:
    app: conceptgraph-backend
spec:
  type: ClusterIP
  selector:
    app: conceptgraph-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
