apiVersion: v1
kind: Service
metadata:
  name: conceptgraph-frontend
  namespace: default
  labels:
    app: conceptgraph-frontend
spec:
  type: LoadBalancer
  selector:
    app: conceptgraph-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None
