apiVersion: v1
kind: Service
metadata:
  name: conceptgraph-neo4j
  namespace: default
  labels:
    app: conceptgraph-neo4j
spec:
  type: ClusterIP
  selector:
    app: conceptgraph-neo4j
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
  sessionAffinity: None
